# Generated by Django 4.2.6 on 2023-11-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_starred", models.BooleanField()),
                ("todoDescription", models.CharField(max_length=250)),
                ("todoTopic", models.CharField(max_length=250)),
            ],
        ),
    ]
